/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BowlSize = { 'large' : null } |
  { 'small' : null } |
  { 'medium' : null };
export interface Customer {
  'id' : bigint,
  'name' : string,
  'mobileNo' : string,
  'preferences' : string,
  'address' : string,
}
export interface DailyStats {
  'revenue' : number,
  'date' : Time,
  'orderCount' : bigint,
}
export interface InventoryItem {
  'id' : bigint,
  'lowStockThreshold' : number,
  'name' : string,
  'unit' : string,
  'quantity' : number,
}
export interface MenuItem {
  'id' : bigint,
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'price' : number,
}
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : OrderStatus,
  'customerPhone' : string,
  'createdAt' : Time,
  'totalAmount' : number,
  'notes' : string,
  'customerId' : Principal,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'quantity' : bigint,
  'unitPrice' : number,
  'menuItemId' : bigint,
}
export type OrderStatus = { 'new' : null } |
  { 'preparing' : null } |
  { 'cancelled' : null } |
  { 'delivered' : null } |
  { 'ready' : null };
export type PaymentStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'overdue' : null };
export interface Subscription {
  'id' : bigint,
  'customerName' : string,
  'status' : SubscriptionStatus,
  'paymentStatus' : PaymentStatus,
  'endDate' : Time,
  'customerPhone' : string,
  'plan' : SubscriptionPlan,
  'price' : number,
  'bowlSize' : BowlSize,
  'totalDeliveriesMade' : bigint,
  'startDate' : Time,
}
export type SubscriptionPlan = { 'monthly' : null } |
  { 'weekly' : null };
export type SubscriptionStatus = { 'active' : null } |
  { 'cancelled' : null } |
  { 'expired' : null } |
  { 'paused' : null };
export type Time = bigint;
export interface TopSellingItem {
  'menuItemName' : string,
  'totalQuantity' : bigint,
  'menuItemId' : bigint,
}
export interface UserProfile { 'name' : string, 'phone' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkAndExpireSubscriptions' : ActorMethod<[], bigint>,
  'createCustomer' : ActorMethod<[string, string, string, string], Customer>,
  'createInventoryItem' : ActorMethod<
    [string, string, number, number],
    InventoryItem
  >,
  'createMenuItem' : ActorMethod<
    [string, string, number, string, string],
    MenuItem
  >,
  'createSubscription' : ActorMethod<
    [string, string, SubscriptionPlan, BowlSize, number],
    Subscription
  >,
  'deleteCustomer' : ActorMethod<[bigint], undefined>,
  'deleteInventoryItem' : ActorMethod<[bigint], undefined>,
  'deleteMenuItem' : ActorMethod<[bigint], undefined>,
  'getActiveSubscriptionCount' : ActorMethod<[], bigint>,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllSubscriptions' : ActorMethod<[], Array<Subscription>>,
  'getAvailableMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomer' : ActorMethod<[bigint], Customer>,
  'getDailyBreakdown' : ActorMethod<[Time, Time], Array<DailyStats>>,
  'getExpiringSubscriptions' : ActorMethod<[], Array<Subscription>>,
  'getLowStockItems' : ActorMethod<[], Array<InventoryItem>>,
  'getOrder' : ActorMethod<[bigint], Order>,
  'getOrdersByStatus' : ActorMethod<[OrderStatus], Array<Order>>,
  'getRevenueAndOrderCount' : ActorMethod<
    [Time, Time],
    { 'revenue' : number, 'orderCount' : bigint }
  >,
  'getTopSellingItems' : ActorMethod<[bigint], Array<TopSellingItem>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[string, string, Array<OrderItem>, string], Order>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleMenuItemAvailability' : ActorMethod<[bigint], MenuItem>,
  'updateCustomer' : ActorMethod<
    [bigint, string, string, string, string],
    Customer
  >,
  'updateInventoryItem' : ActorMethod<
    [bigint, string, string, number, number],
    InventoryItem
  >,
  'updateMenuItem' : ActorMethod<
    [bigint, string, string, number, string, string],
    MenuItem
  >,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], Order>,
  'updateStockLevel' : ActorMethod<[bigint, number], InventoryItem>,
  'updateSubscription' : ActorMethod<
    [bigint, BowlSize, number, PaymentStatus],
    Subscription
  >,
  'updateSubscriptionStatus' : ActorMethod<
    [bigint, SubscriptionStatus],
    Subscription
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];