/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Customer = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'mobileNo' : IDL.Text,
  'preferences' : IDL.Text,
  'address' : IDL.Text,
});
export const InventoryItem = IDL.Record({
  'id' : IDL.Nat,
  'lowStockThreshold' : IDL.Float64,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'quantity' : IDL.Float64,
});
export const MenuItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});
export const SubscriptionPlan = IDL.Variant({
  'monthly' : IDL.Null,
  'weekly' : IDL.Null,
});
export const Plan = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'price350gm' : IDL.Float64,
  'price500gm' : IDL.Float64,
  'planType' : SubscriptionPlan,
  'price250gm' : IDL.Float64,
});
export const BowlSize = IDL.Variant({
  'large' : IDL.Null,
  'small' : IDL.Null,
  'medium' : IDL.Null,
});
export const SubscriptionStatus = IDL.Variant({
  'active' : IDL.Null,
  'cancelled' : IDL.Null,
  'expired' : IDL.Null,
  'paused' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'overdue' : IDL.Null,
});
export const Time = IDL.Int;
export const Subscription = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : SubscriptionStatus,
  'paymentStatus' : PaymentStatus,
  'endDate' : Time,
  'customerPhone' : IDL.Text,
  'plan' : SubscriptionPlan,
  'price' : IDL.Float64,
  'bowlSize' : BowlSize,
  'totalDeliveriesMade' : IDL.Nat,
  'startDate' : Time,
});
export const OrderStatus = IDL.Variant({
  'new' : IDL.Null,
  'preparing' : IDL.Null,
  'cancelled' : IDL.Null,
  'delivered' : IDL.Null,
  'ready' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Float64,
  'menuItemId' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'customerPhone' : IDL.Text,
  'createdAt' : Time,
  'totalAmount' : IDL.Float64,
  'notes' : IDL.Text,
  'customerId' : IDL.Principal,
  'items' : IDL.Vec(OrderItem),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const DailyStats = IDL.Record({
  'revenue' : IDL.Float64,
  'date' : Time,
  'orderCount' : IDL.Nat,
});
export const TopSellingItem = IDL.Record({
  'menuItemName' : IDL.Text,
  'totalQuantity' : IDL.Nat,
  'menuItemId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkAndExpireSubscriptions' : IDL.Func([], [IDL.Nat], []),
  'createCustomer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Customer],
      [],
    ),
  'createInventoryItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
      [InventoryItem],
      [],
    ),
  'createMenuItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
      [MenuItem],
      [],
    ),
  'createPlan' : IDL.Func(
      [IDL.Text, SubscriptionPlan, IDL.Float64, IDL.Float64, IDL.Float64],
      [Plan],
      [],
    ),
  'createSubscription' : IDL.Func(
      [IDL.Text, IDL.Text, SubscriptionPlan, BowlSize, IDL.Float64],
      [Subscription],
      [],
    ),
  'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
  'deleteInventoryItem' : IDL.Func([IDL.Nat], [], []),
  'deleteMenuItem' : IDL.Func([IDL.Nat], [], []),
  'deletePlan' : IDL.Func([IDL.Nat], [], []),
  'getActiveSubscriptionCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllPlans' : IDL.Func([], [IDL.Vec(Plan)], ['query']),
  'getAllSubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
  'getAvailableMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomer' : IDL.Func([IDL.Nat], [Customer], ['query']),
  'getDailyBreakdown' : IDL.Func(
      [Time, Time],
      [IDL.Vec(DailyStats)],
      ['query'],
    ),
  'getExpiringSubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
  'getLowStockItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
  'getOrdersByStatus' : IDL.Func([OrderStatus], [IDL.Vec(Order)], ['query']),
  'getPlanEnrollmentCounts' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'planId' : IDL.Nat,
            'planName' : IDL.Text,
            'enrolledCount' : IDL.Nat,
          })
        ),
      ],
      ['query'],
    ),
  'getRevenueAndOrderCount' : IDL.Func(
      [Time, Time],
      [IDL.Record({ 'revenue' : IDL.Float64, 'orderCount' : IDL.Nat })],
      ['query'],
    ),
  'getTopSellingItems' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(TopSellingItem)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(OrderItem), IDL.Text],
      [Order],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleMenuItemAvailability' : IDL.Func([IDL.Nat], [MenuItem], []),
  'updateCustomer' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Customer],
      [],
    ),
  'updateInventoryItem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
      [InventoryItem],
      [],
    ),
  'updateMenuItem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
      [MenuItem],
      [],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [Order], []),
  'updatePlan' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        SubscriptionPlan,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Bool,
      ],
      [Plan],
      [],
    ),
  'updateStockLevel' : IDL.Func([IDL.Nat, IDL.Float64], [InventoryItem], []),
  'updateSubscription' : IDL.Func(
      [IDL.Nat, BowlSize, IDL.Float64, PaymentStatus],
      [Subscription],
      [],
    ),
  'updateSubscriptionStatus' : IDL.Func(
      [IDL.Nat, SubscriptionStatus],
      [Subscription],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Customer = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'mobileNo' : IDL.Text,
    'preferences' : IDL.Text,
    'address' : IDL.Text,
  });
  const InventoryItem = IDL.Record({
    'id' : IDL.Nat,
    'lowStockThreshold' : IDL.Float64,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'quantity' : IDL.Float64,
  });
  const MenuItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  const SubscriptionPlan = IDL.Variant({
    'monthly' : IDL.Null,
    'weekly' : IDL.Null,
  });
  const Plan = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'price350gm' : IDL.Float64,
    'price500gm' : IDL.Float64,
    'planType' : SubscriptionPlan,
    'price250gm' : IDL.Float64,
  });
  const BowlSize = IDL.Variant({
    'large' : IDL.Null,
    'small' : IDL.Null,
    'medium' : IDL.Null,
  });
  const SubscriptionStatus = IDL.Variant({
    'active' : IDL.Null,
    'cancelled' : IDL.Null,
    'expired' : IDL.Null,
    'paused' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'overdue' : IDL.Null,
  });
  const Time = IDL.Int;
  const Subscription = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : SubscriptionStatus,
    'paymentStatus' : PaymentStatus,
    'endDate' : Time,
    'customerPhone' : IDL.Text,
    'plan' : SubscriptionPlan,
    'price' : IDL.Float64,
    'bowlSize' : BowlSize,
    'totalDeliveriesMade' : IDL.Nat,
    'startDate' : Time,
  });
  const OrderStatus = IDL.Variant({
    'new' : IDL.Null,
    'preparing' : IDL.Null,
    'cancelled' : IDL.Null,
    'delivered' : IDL.Null,
    'ready' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Float64,
    'menuItemId' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'customerPhone' : IDL.Text,
    'createdAt' : Time,
    'totalAmount' : IDL.Float64,
    'notes' : IDL.Text,
    'customerId' : IDL.Principal,
    'items' : IDL.Vec(OrderItem),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'phone' : IDL.Text });
  const DailyStats = IDL.Record({
    'revenue' : IDL.Float64,
    'date' : Time,
    'orderCount' : IDL.Nat,
  });
  const TopSellingItem = IDL.Record({
    'menuItemName' : IDL.Text,
    'totalQuantity' : IDL.Nat,
    'menuItemId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkAndExpireSubscriptions' : IDL.Func([], [IDL.Nat], []),
    'createCustomer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Customer],
        [],
      ),
    'createInventoryItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
        [InventoryItem],
        [],
      ),
    'createMenuItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
        [MenuItem],
        [],
      ),
    'createPlan' : IDL.Func(
        [IDL.Text, SubscriptionPlan, IDL.Float64, IDL.Float64, IDL.Float64],
        [Plan],
        [],
      ),
    'createSubscription' : IDL.Func(
        [IDL.Text, IDL.Text, SubscriptionPlan, BowlSize, IDL.Float64],
        [Subscription],
        [],
      ),
    'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
    'deleteInventoryItem' : IDL.Func([IDL.Nat], [], []),
    'deleteMenuItem' : IDL.Func([IDL.Nat], [], []),
    'deletePlan' : IDL.Func([IDL.Nat], [], []),
    'getActiveSubscriptionCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllPlans' : IDL.Func([], [IDL.Vec(Plan)], ['query']),
    'getAllSubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
    'getAvailableMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomer' : IDL.Func([IDL.Nat], [Customer], ['query']),
    'getDailyBreakdown' : IDL.Func(
        [Time, Time],
        [IDL.Vec(DailyStats)],
        ['query'],
      ),
    'getExpiringSubscriptions' : IDL.Func(
        [],
        [IDL.Vec(Subscription)],
        ['query'],
      ),
    'getLowStockItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
    'getOrdersByStatus' : IDL.Func([OrderStatus], [IDL.Vec(Order)], ['query']),
    'getPlanEnrollmentCounts' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'planId' : IDL.Nat,
              'planName' : IDL.Text,
              'enrolledCount' : IDL.Nat,
            })
          ),
        ],
        ['query'],
      ),
    'getRevenueAndOrderCount' : IDL.Func(
        [Time, Time],
        [IDL.Record({ 'revenue' : IDL.Float64, 'orderCount' : IDL.Nat })],
        ['query'],
      ),
    'getTopSellingItems' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(TopSellingItem)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(OrderItem), IDL.Text],
        [Order],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleMenuItemAvailability' : IDL.Func([IDL.Nat], [MenuItem], []),
    'updateCustomer' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Customer],
        [],
      ),
    'updateInventoryItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
        [InventoryItem],
        [],
      ),
    'updateMenuItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
        [MenuItem],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [Order], []),
    'updatePlan' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          SubscriptionPlan,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Bool,
        ],
        [Plan],
        [],
      ),
    'updateStockLevel' : IDL.Func([IDL.Nat, IDL.Float64], [InventoryItem], []),
    'updateSubscription' : IDL.Func(
        [IDL.Nat, BowlSize, IDL.Float64, PaymentStatus],
        [Subscription],
        [],
      ),
    'updateSubscriptionStatus' : IDL.Func(
        [IDL.Nat, SubscriptionStatus],
        [Subscription],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };